PRAGMA foreign_keys = ON;

CREATE TABLE INTERFACE(
    INTERFACE_ID TEXT[20] PRIMARY KEY NOT NULL,
    SUBNET TEXT[60] NOT NULL,
    UNIQUE(INTERFACE_ID)
);

CREATE TABLE HOST(
    HOST_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    HOSTNAME TEXT[60] NOT NULL,
    MAC_ADDR TEXT[60] NOT NULL,
    LAST_IP TEXT[60] NOT NULL,
    LAST_ONLINE DATETIME NOT NULL,
    UNIQUE(HOSTNAME)
);
